### ISSUE TITLE
SyntaxError: invalid syntax FORE

### ISSUE THREAD

**Issue by assh0le1** [snooppr/snoop#1]
Вероятно дело в кривых руках, но всё же не смог из коробки заставить заработать snoop. При установке всех зависимостей все равно остается ошибка вида SyntaxError: invalid syntax
```
chto@home:~/snoop# python3 snoop.py --help
  File "snoop.py", line 73
    Fore.GREEN + f"] {title}" +
                            ^
SyntaxError: invalid syntax
chto@home~/snoop#
```
В чем моя проблема?
Python 3.5.2
pip 20.0.2 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

**Comment by snooppr** [comment]
Прочитайте пожалуйста **внимательнее** Readme:
> Примечание: Требуемая версия python 3.6 и выше.

> Project Snoop работает на OS GNU/Linux & Android/Termux.

**Comment by assh0le1** [comment]
Ты совершенно прав, а мне ужасно стыдно что читал недостаточно внимательно.
