### ISSUE TITLE
Добавить __pycache__ в gitignore

### ISSUE THREAD

**Issue by samdark** [snooppr/snoop#11]
Кеш питона не игнорится. Приходится сносить чтобы сделать git pull.

**Comment by snooppr** [comment]
`git pull` работает хорошо на Deb

На этом еще и завязана опция обновления.
`git stash && git pull`
![1](https://user-images.githubusercontent.com/61022210/74655446-6d148c80-519d-11ea-9f8d-924f75990c12.png)




С каким дистрибутивом у вас проблема?

**Comment by samdark** [comment]
Я про git stash. Чтобы его не делать и чтобы случайно потом не влить содержимое __pycache__ в репозиторий, директорию можно добавить в `.gitignore`.  Вот примерно так: https://github.com/django/django/blob/master/.gitignore#L9

**Comment by snooppr** [comment]
Спрятал.
