### ISSUE TITLE
Difference with Sherlock?

### ISSUE THREAD

**Issue by KeizerDev** [snooppr/snoop#13]
Hey,

I'm wondering what's the difference between this project and https://github.com/sherlock-project/sherlock.

Thanks!

**Comment by snooppr** [comment]
Hey.  This is Fork Sherlocka (this is reported in the license, changelog, readme).  I contributed at least 1/3 of all sites to Sherlock, but at some point, they began to do this less often.  The main difference is that Snoop will be focused on searching in the CIS locations (ru).  To other differences, Snoop already has a larger database.  New options have also been added (updates, sorting, informative output with date, and music).  You can familiarize yourself with the changes in the changelog.txt file in more detail (a translation into your language should be available in Chrome)
https://raw.githubusercontent.com/snooppr/snoop/master/changelog.txt
