### ISSUE TITLE
Crash in wsl

### ISSUE THREAD

**Issue by SunnyCapt** [snooppr/snoop#14]
The script crashes when executed in WSL because it does not have access to the pc hardware. Please fix or dont use `playsound`.

**Comment by snooppr** [comment]
Checked work on On GNU / Linux; Windows7 32 / Windows10 Home 64 cmd works without problems.

As for the WSL Linux subsystem in Windows 10, I have no way to work on such platforms.
I'm not sure if this needs a patch.

You can use cmd (Windows) or install Snoop with the module disabled from the Termux branch
git clone https://github.com/snooppr/snoop -b termux
