### ISSUE TITLE
Snoop на Windows 7 (64 bit)

### ISSUE THREAD

**Issue by i-mihal** [snooppr/snoop#15]
Здравствуйте.
Попробовал запустить Snoop на Win7 Pro / 64 bit / Python 3.8.1

При запуске сразу вылетает ошибка:
-------------------------------------
Traceback (most recent call last):
  File "snoop.py", line 40, in <module>
    locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')
  File "C:\Users\i_mihal\AppData\Local\Programs\Python\Python38-32\lib\locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
-------------------------------------
Это вот тут в "snoop.py":
-------------------------------------
if sys.platform == 'win32':
    locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')
-------------------------------------
Я на Питон не пишу, поэтому просто погуглил.
Пишут, что 'ru_RU.UTF-8' в setlocale используется только для *nix-систем, а в винде надо писать 'ru' или вообще пустые скобки и тогда setlocale сама там всё установит в соответствии с виндовыми настройками.

В общем я попробовал менять строку locale.setlocale(locale.LC_ALL, 'ru_RU.UTF-8')
на такую -> locale.setlocale(locale.LC_ALL,'ru')
и на такую -> locale.setlocale(locale.LC_ALL,'')

 оба варианта работают, программа не вылетает, текст выводит в консоль по-русски, по сайтам вроде ищет, всё нормально.

**Comment by snooppr** [comment]
Верно, я получил подобную ошибку на Win7/32, поправил здесь, обновитесь, протестируйте пожалуйста.
https://github.com/snooppr/snoop/commit/c0b233e264f29fff2b4d0e980c7419ffba99f9d9

**Comment by se16n** [comment]
Why it needs locale at all anyway?

**Comment by i-mihal** [comment]
Обновился.
Теперь этот фрагмент выглядит так:

if sys.platform == 'win32':
    locale.setlocale(locale.LC_ALL, '')
    init()

и всё нормально работает в Win7/64.

Но теперь у меня вопрос, зачем тут еще "колорамовская" строка init(), её ведь раньше не было и всё цветное работало?
Тем более в main() этот init() вызывается еще раз вот так:
    init(autoreset=True)
и весь дальнейшие print (в том числе и при работе программы в винде) выполняются уже после этого init(autoreset=True)

Но это я так, просто, спрашиваю. Можно и не отвечать, если я фигню несу :)

**Comment by snooppr** [comment]
> её ведь раньше не было и всё цветное работало?

Не все, версия в snoop в баннере не должна была краситься, а вместо триколора V1.0.0_rus
должна была выглядеть кодом, что- то вроде этого [\033[37mv1.\033[34m0.0\033[31m_rus\033[0m]

Изначально, да красилось всё (в GNU/Linux), в Windows — нет.

Теперь красится всё и везде
https://github.com/snooppr/snoop/commit/e7cb4756b5a17e9f4513ed55d2717cef859c54e4

Если проблема решена с win, я закрываю "issues"

**Comment by i-mihal** [comment]
OK, закрываете, так закрываете :)

Вообще написал, что "всё цветное работало" потому, что я пробовал убирать первый init(), который в if'е и запускать программу. При этом версия v1.0.8_rus всё равно была раскрашена, хотя получается, что перед первым print не было вызова колорамовского init().
Я даже пробовал перезагрузиться, на всякий случай и потом запустить snoop.py без строки init(), при этом версия раскрашена. По крайней мере под Win7 раскрашена. 
А init() первый стоит как раз в условии про win32, вот я и подумал, может он вообще не нужен.
Или просто сделать init() не в условии if sys.platform == 'win32', а просто отдельной строкой init(autoreset=True) чтобы init был только один, в одном месте, перед первым print'ом.

**Comment by snooppr** [comment]
> пробовал убирать первый init(), который в if'е и запускать программу. При этом версия v1.0.8_rus всё равно была раскрашена

Ммм, у меня на win7(32) без init() не красило версию и выдавало код, который писал выше, поэтому его туда и ставил. Так и должно было быть по документации colorama.
Почему у вас красило не знаю.

**Comment by i-mihal** [comment]
Ясно. 
По идее да - **init** нужен. 
Но у меня версию красило без него, я прям конкретно проверил.

Вообще, я имел ввиду, может вместо двух **init** (один в начале в ветви **if** и второй - ниже, в **main**) сделать только один в начале, но вынести его из IF'a).

Ну, типа, убрать **init** из **main**, а вместо вот этого:

`if sys.platform == 'win32':
    locale.setlocale(locale.LC_ALL, '')
    init()
`
сделать так:

`if sys.platform == 'win32':
    locale.setlocale(locale.LC_ALL, '')
init(autoreset=True)
`

**Comment by i-mihal** [comment]
Добрый вечер.

Теперь init у Вас один, все хорошо.
Есть еще вопрос.
Первое, что выполняется в программе это:

if sys.platform == 'win32':
....locale.setlocale(locale.LC_ALL, '')

То есть проверяется не запущена ли программа под **win32** и вызывается **setlocale**

Но потом ниже в функциях update_snoop() и main() в ветвях, где проверяется **if sys.platform == 'win32'** есть еще два вызова **locale.setlocale(locale.LC_ALL, '')**
Они теперь не нужны, так как в самом начале программы уже проверяется, не запущена ли программа под **win32** и вызывается **setlocale** при необходимости.
