### ISSUE TITLE
Working not correct

### ISSUE THREAD

**Issue by UxtUaHgp-BeZsTraJllHuU** [snooppr/snoop#18]
After Allmylinks file doesn't work
![Screenshot_20200222-152154](https://user-images.githubusercontent.com/45915286/75093059-2a7cf680-5587-11ea-8c43-03ab3fdd22a1.png)
![Screenshot_20200222-152200](https://user-images.githubusercontent.com/45915286/75093061-2bae2380-5587-11ea-9391-faecda089ddb.png)
![Screenshot_20200222-152205](https://user-images.githubusercontent.com/45915286/75093062-2c46ba00-5587-11ea-97cd-a23bdb4f0ab5.png)

**Comment by snooppr** [comment]
Read carefully Readme.
Snoop on Termux works. For him, see a separate branch.

This is verified.
https://github.com/snooppr/snoop/tree/termux

**Comment by UxtUaHgp-BeZsTraJllHuU** [comment]
Sorry, but I can't find issue

**Comment by snooppr** [comment]
You must install the Snoop version for termux.  
This is done like this:
`git clone https://github.com/snooppr/snoop -b termux`
