### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ricary37** [snooppr/snoop#19]
Windows 10 x64, Python 3.8.1 x64.
выдает ошибку в конце:
```
...
[-] Zhihu: Увы!
Traceback (most recent call last):
  File "snoop.py", line 831, in <module>
    main()
  File "snoop.py", line 765, in main
    file.write(date.strftime("%d/%m/%Yг. в %Hч.%Mм.%Sс."))
UnicodeEncodeError: 'locale' codec can't encode character '\u0433' in position 8: encoding 
```

**Comment by snooppr** [comment]
Работоспоспособность Snoop только что проверил на Windows 10 Home x 64
python v3.7.6.
![win10](https://user-images.githubusercontent.com/61022210/75148768-7c518800-5711-11ea-85c5-4f10228aa316.png)

Это также работает на Windows 7 x 32/64
Подобной ошибки не возникает.
 Какая у вас версия snoop?
