### ISSUE TITLE
Как добавлять сайты в базу?

### ISSUE THREAD

**Issue by i-mihal** [snooppr/snoop#22]
Здравствуйте.
Хотел попробовать добавить в базу сайты, на которых часто бываю (популярные сайты по ремонту цифровой техники) в связи с чем вопрос: мне просто смотреть на файл example_data.json и пытаться понять, как добавить свой сайт в базу или я пропустил и где то есть описание процесса?
Пробовал экспериментировать, добавлять, но то работает, то нет.

**Comment by snooppr** [comment]
Здравствуйте.
Да, файл example_data.json содержит всевозможные примеры для добавления своего сайта (3 примера).

Примеры.
1) Делаете запрос/ответ к сайту, например с помощью утилиты 'Curl'
`$ curl -I https://url/username && curl -I https://url/несуществующийusername`
Если в первом случае получаете ответ типо 
> HTTP/1.1 200 OK

а во втором случае

> HTTP/1.1 404 Not Found

То добавляете сайт в **WebsiteName1**

2) Тот же Curl
`$ curl -I https://url/username && curl -I https://url/несуществующийusername`
Если в первом случае получаете ответ типо 
> HTTP/1.1 200 OK

а во втором случае

> HTTP/2 302 

То добавляете сайт в **WebsiteName2** ('302 статус перенаправление". и указываете, в 'errorUrl', на какую страницу вас перенаправляют).

3) Тот же Curl
`$ curl -I https://url/username && curl -I https://url/несуществующийusername`
Если в в обоих случаях получаете

> HTTP/1.1 200 OK

То, Открываете в браузере, например ПКМ-просмотреть код страницы, и ищете (на несуществующем никнейме) 

> <title>Text

Которого не должно быть (по этой же схеме) на существующем никнейме.
'<title>Text' — добавляете в **WebsiteName3**
'errorMsg'
С этим методом несколько подвохов, например, в ru локации вы можете в коде страницы увидеть

> <title>Текст 

а в en локации

> <title>Text
В редких случаях, почти никогда, проблему можно решить добавлением ( "Accept-Language": "en-US,en;q=0.9") .
Поэтому для гарантии я добавил второй ключ 'errorMsg2'.
Оба случая  (Текст в en/ru из кода страницы) добавляете
в errorMsg и errorMsg2 (**смотри пример Ebay в data.json**).
Если в коде страницы кириллица, то пишите прямо кириллицей в 'errorMsg2', не обьязательно переводить в \u0412\....

Также может быть подвох, когда код страницы в обоих случаях идентичный (**смотри пример SportsTracker**)

В таком случае у сайта можно отыскать api, с помощью сканера, например, валидатора [ссылок](https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.sports-tracker.com%2Fview_profile%2Fusername&hide_type=all&depth=&check=Check)

Вся движуха происходит в 'urlProbe'
Все что вы вводите (существующий/несуществующий username) отображается в api, от туда текст берёте и вставляете в 'errorMsg/2' и указываете этот api в 'urlProbe'.

Многие сайты могут отображать в url — хэш/соль/id и тд, но не username, тут можно поманипулировать прямо в строке браузера и получить вместо 
хэш/соль/id - username (но не всегда).
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

> популярные сайты по ремонту цифровой техники

К сожалению все популярные сайты по электронике я давно уже прочекал и добавить их не удалось, как и многие остальные, например, эзотерику или порталы о медицине и тд.
То есть не все сайты можно добавить в базу snoop.

**Comment by i-mihal** [comment]
спасибо за подробные объяснения, поэкспериментирую
