### ISSUE TITLE
How can I get Snoop to skip a website that is not working?

### ISSUE THREAD

**Issue by shitheadexpress** [snooppr/snoop#23]
Great program
Is there anyway I can get Snoop to skip a website that is not working? Archive.org for example is down for maintenance, how can I get it to continue doing the search past this?

Отличная программа
Могу ли я заставить Snoop пропустить сайт, который не работает? Например, Archive.org недоступен для обслуживания, как я могу заставить его продолжить поиск после этого?

**Comment by snooppr** [comment]
> Great program

I agree.

When you run snoop, you get an example of “how to use it”

(If GNU / Linux)
`$ python3 snoop.py -t 9 username`

The option '**-t 9**' is just what you need in your case; it does the following:
If for some reason the site does not respond (there may be many reasons) snoop waits for **9 seconds**, and if the site does not respond within this time, then snoop moves on.

Also if you type
`$ snoop -h`

You will get help where this moment is highlighted in red.
Please upload this help to the translator, this will help you to get the most out of the search.

**Comment by shitheadexpress** [comment]
Thank you. I think it was the translation of the front-page. That explains in much better. Thank you for your time and work.

Спасибо. Я думаю, что это был перевод первой страницы. Это объясняет гораздо лучше. Спасибо за ваше время и работу.
