### ISSUE TITLE
colorama

### ISSUE THREAD

**Issue by antailyaqwer** [snooppr/snoop#3]
Профан в линуксе, так что не судите строго. Попытался запустить скрипт - выдало ошибку насчет модуля requests. Погуглил, понял, что этот модуль не работает с версией 3.8. Попробовал запустить 3.6 (и 3.7) - теперь проблемы с модулем colorama. Вроде и переустановил, и всё - результат тот же, библиотека не найдена. ЧЯДНТ?

**Comment by StarLabsUA** [comment]
Такая же проблема. питон 3.8
Термукс тоже самое кстати говорит

**Comment by sweet90** [comment]
Traceback (most recent call last):
  File "d:/snoop/snoop.py", line 762, in <module>
    main()
  File "d:/snoop/snoop.py", line 428, in main
    cop = copyright.read()
  File "C:\Users\username\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1444: character maps to <undefined>

**Comment by StarLabsUA** [comment]
тоже самое

**Comment by snooppr** [comment]
> тоже самое

Тоже самое что? Тоже на Windows запускаете? Читайте Readme.

**Comment by sweet90** [comment]
> > тоже самое
> 
> Тоже самое что? Тоже на Windows запускаете? Читайте Readme.

под WSL с убунтой тоже не запускается

**Comment by snooppr** [comment]
> > > тоже самое
> > 
> > 
> > Тоже самое что? Тоже на Windows запускаете? Читайте Readme.
> 
> под WSL с убунтой тоже не запускается

По логам вижу, что запускаете на Windows.
Что с Убунтой никто не знает.
