### ISSUE TITLE
Критическая ошибка при Ошибка соединения при использовании Snoop в VitualBox

### ISSUE THREAD

**Issue by ComradeAx0n** [snooppr/snoop#31]
Проблема на kali linux 2020.2a в virtualbox

[-] Ошибка соединения: PokerstrategyCOM 
━━━╺━━  58%                                                                                                       
** (python3:1842): CRITICAL **: 13:32:58.928: file gstaudioringbuffer.c: line 2048 (gst_audio_ring_buffer_set_channel_positions): should not be reached

**Comment by snooppr** [comment]
Подскажите, вы запускаете из исходников или готовой сборки?
(приложите команду на запуск).

Если из исходников, то какая версия python у вас установлена?

Эта ошибка свзана с заброшенным аудиомодулем playsound (ошибки я перехватываю...
https://github.com/snooppr/snoop/blob/master/snoop.py#L158
мне нужно больше информации).

**Comment by snooppr** [comment]
Отсутствие каких-либо запрошенных деталей.
Закрыто.
