### ISSUE TITLE
POP Up results Music and Full English version

### ISSUE THREAD

**Issue by leemoh** [snooppr/snoop#34]
English Language and Removing the pop up sound.

**Comment by snooppr** [comment]
What do you have in mind?

**Comment by leemoh** [comment]
The Html result to be in English or to have an English Alternative. There is also that sound it makes after the browser opens, I did not find a way to disable it. Thanks

**Comment by snooppr** [comment]
1. Snoop (Demo/Full version) has English version support.
HTML Report
![1](https://user-images.githubusercontent.com/61022210/89108408-dd0f8a00-d440-11ea-8d57-5e1e0d4ddc70.png)

Download Snoop EN version https://github.com/snooppr/snoop/releases
![2](https://user-images.githubusercontent.com/61022210/89108427-1647fa00-d441-11ea-9826-3139dff3d866.png)

2. The sound is muted with the '-n' option, for example, 'snoop -n username'.
Please read the English documentation, an example for Snoop for Windows: snoop.exe --help

**Comment by snooppr** [comment]
1. Snoop (Demo/Full version) has English version support.
HTML Report
![1 cleaned](https://user-images.githubusercontent.com/61022210/89108586-755a3e80-d442-11ea-9104-1117814da5dd.png)

Download Snoop EN version https://github.com/snooppr/snoop/releases
![2](https://user-images.githubusercontent.com/61022210/89108427-1647fa00-d441-11ea-9826-3139dff3d866.png)

2. The sound is muted with the '-n' option, for example, 'snoop -n username'.
Please read the English documentation, an example for Snoop for Windows: snoop.exe --help
