### ISSUE TITLE
Windows Defender detects Trojan:Win32/Zpevdo.B in executable

### ISSUE THREAD

**Issue by S0Ulle33** [snooppr/snoop#35]
Trying to launch executable from [EN.Snoop.for.Windows.rar](https://github.com/snooppr/snoop/releases/download/V1.2.1E_10_july_2020/EN.Snoop.for.Windows.rar) gives this message from Windows Defender:
![image](https://user-images.githubusercontent.com/29702137/90340732-26083680-e01c-11ea-9c53-597c11d24dd5.png)

I guess this is a false positive, because executable isn't signed?

**Comment by snooppr** [comment]
False alarm
