### ISSUE TITLE
Downloading and Installing typing_extensions

### ISSUE THREAD

**Issue by Lionde002** [snooppr/snoop#38]
How to install these modules i tried a lot but that's not working,I'm using Windows Subsystem for Linux(Kali Linux Rolling)

ERROR: ufonet 1.5 requires GeoIP>=1.3.2, which is not installed.
ERROR: ufonet 1.5 requires pycrypto>=2.6.1, which is not installed.
ERROR: clarifai 2.6.2 has requirement configparser<4,>=3.5, but you'll have configparser 5.0.0 which is incompatible.

I'll leave you some images...

![Kali Linux 18_09_2020 00_32_15](https://user-images.githubusercontent.com/47432670/93515663-96211980-f946-11ea-9eea-9b857bb902f9.png)

**Comment by snooppr** [comment]
You shouldn't be using WSL / 2.  These crutches won't help you.

If you want to build and run Snoop from source, then on Windows OS use cmd (or powershell), not crutches.  The working moment is scheduled in the documentation.  Snoop has ready-made assemblies (no need for Python, see release).

If you want Snoop specifically for GNU / Linux, then you must have a real Linux distribution, not the "wsl" part.  This is justified and it is widely known.
