### ISSUE TITLE
Поиск по регулярным выражениям

### ISSUE THREAD

**Issue by hIMEI29A** [snooppr/snoop#41]
Иногда пользователи регистрируются в разных соцсетях, внося небольшие изменения в юзернэйм. К примеру, `username`, `user_name`, `us3r_n@me`, `_user_nam3_` и т.д. Можно реализовать поиск по регулярным выражениям, чтобы не прописывать в командной строке все эти варианты. В данном примере - `_?us(e|3)r_?n(a|@)m(e|3)_?`
Могу взяться за эту задачу. Как раз учу Пайтон.

**Comment by snooppr** [comment]
Это вызовет нагрузку на поиск (для сайтов и поиск может быть частично отвергнут), вероятно, придется добавить к новому ключу и top сайтов. 
Выбрать самые топовые (не по рейтингу Alexa) и лояльные к парсингу сайты, в таком случае реализовать и маску по имени.
