### ISSUE TITLE
How to Install English Snoop on Linux

### ISSUE THREAD

**Issue by Mrtoolkey** [snooppr/snoop#48]
Sorry for the trouble but, how do I install the English version of snoop on Linux. I see there is only one file but, what command is used to install? Snoop, snoop.sig, and note.txt.

**Comment by snooppr** [comment]
Hello, launching like any other cli program in the terminal. Read the GNU/Linux basics. (launch, drag the file into the terminal window, enter).

Отправлено из мобильного клиента ProtonMail

-------- Исходное сообщение --------
В 11 сент. 2021 г., 23:50, Mrtoolkey написано:
