### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by CompuRoot** [snooppr/snoop#49]
Snoop version: `V1.3.1_7_November_2021 `
--- 

This is really **wrong assumption** that any program can write anywhere it likes, as well assumption that any program will run under administrative account ! 

I'm pretty sure that scraping internet don't need such permissions.

```
PermissionError: [WinError 5] Access is denied: 'c:/snoop'
```

**Comment by snooppr** [comment]
> ## Snoop version: `V1.3.1_7_November_2021 `
> 
> This is really **wrong assumption** that any program can write anywhere it likes, as well assumption that any program will run under administrative account !
> 
> I'm pretty sure that scraping internet don't need such permissions.
> 
> ```
> PermissionError: [WinError 5] Access is denied: 'c:/snoop'
> ```

1) `snoop.exe` does not require administrator privileges, it should work normally (at least on my Windows 7 32bit OS it does). For example, I put together a test assembly admin_snoop.exe, which requires administrator privileges and differs from the build in the release (requires admin rights, [please check](https://disk.yandex.ru/d/RTjk8ewOZ_FzMQ)).
Just in case, I rebuilt the no_admin_snoop.exe assembly, I also ask [you to check](https://disk.yandex.ru/d/8YM2A9FaBmJHlw) (it does not require administrator privileges).

2) `snoop.exe` writes to `c:\snoop` (files reports [txt, csv, html] with search results username or results of plugins work), and also places materials (.mp3; png; config) in the directory for a nice html report.
This is necessary, so you are mistaken that snoop only needs an internet connection.

**Comment by CompuRoot** [comment]
- Regarding N1: 
I meant: requiring administrative permissions without a reason is as bad (in the same category) as assumption that you can create folders in root directory on any unknown machine. I'm sorry for confusion.

- Regarding N2:
Nowadays operation systems are multi-tenant, the worse time of Windows 98 and below are gone. You can't assume that computer is just a device glued to particular person. Even home computer should have at least two accounts, - administrative and standard user for normal use if one wants a secure setup. In corporate environment it is "must have" requirement, each user **must have** its own, separated from others **restricted** account.  If anyone would be allowed to create in root folder any folders, it will be a mess and path to the hell's security, that's why writing to root directory is prohibited in domains. Another reason, - in corporate environment where computers are part of domain, there very often applied "folder redirection" or/and "roaming" features which allows users to use any computer in domain and having their settings and files on any domain's computers. Besides of user's convenience, such setup is also allows to keep all user's data on the server where all data are subject for centralized backup. With your approach, - it is impossible to keep users data safe and private. I suggest you to read **environment** variables such as `USERPROFILE` and create `snoop` directory there (`%USERPROFILE%\Documents` folder is appropriate candidate for example, so it will follow user on any computer if folder redirection is working ) or better yet, use `%LOCALAPPDATA%\Software\snoop` if you want to enforce data to keep locally on particular computer or `%APPDATA%\Software\snoop`  to allow data roaming.

**Comment by snooppr** [comment]
Thanks for the detailed answer!  

I store data/reports in a user environment (as you wrote about Windows) in GNU/Linux, but neglected it for Windows users.
In the near future I will correct the directory, rewrite the documentation and run the tests and unsubscribe here.

This was helpful advice. Gratitude!

**Comment by snooppr** [comment]
Updated assemblies. You can try to check:
[Snoop EN_win](https://github.com/snooppr/snoop/releases/download/V1.3.1A_11_November_2021/EN.Snoop.for.Windows.OLD.rar)
[Snoop RU_win](https://github.com/snooppr/snoop/releases/download/V1.3.1A_11_November_2021/RU.Snoop.for.Windows.rar)

**Comment by snooppr** [comment]
I close the issues as it is solved.
