### ISSUE TITLE
Wrong permission under Linux

### ISSUE THREAD

**Issue by CompuRoot** [snooppr/snoop#50]
snoop version: `v1.3.1`
---

`snoop` unpacking its files with unappropriated permissions in folder: `~/snoop/web`

files with extensions: `*.css`, `*.js`, `*.mp3`, `*.png` - **must not be executable** !

**Comment by snooppr** [comment]
Thank you for your observation.

The rights that confuse - restored to the correct ones for the directory and for the files (directory 755; files 644).
The reason for changing the files lay in the compilation of the build version (for pyinstaller mp3 and other files are added as binary and after unpacking the modified files are copied). Now I check and reassign the permissions of the directory/files on 'web' back to valid when copying files from the temporary directory to 'web'.

Please check: delete the directory '/home/user/snoop'
and use the update I downloaded today:
https://github.com/snooppr/snoop/releases/download/V1.3.1_7_November_2021/RU.Snoop.for.GNU_Linux.rar
or
https://github.com/snooppr/snoop/releases/download/V1.3.1_7_November_2021/EN.Snoop.for.GNU_Linux.OLD.rar

Everything should be Feng Shui on GNU/Linux.

**Comment by CompuRoot** [comment]
Thanks for taking time to look at this issue !
Closing issue.
