### ISSUE TITLE
Не ищет когда есть точка в нике

### ISSUE THREAD

**Issue by Bodyhealer** [snooppr/snoop#58]
nickname, содержащий [.] и не являющийся email, невалидный...
пропуск

Есть ник с точкой, но поиск по нему не происходит из-за того, такие ники отбрасываются.

**Comment by snooppr** [comment]
При поиске я ограничиваю некоторые спецсимволы, например, "точка" или "решётка" (но не все).
Это сделано специально, чтобы пользователь не получал в подавляющем большинстве случаев ложные результаты.
