### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by samdark** [snooppr/snoop#6]
```
[-] Zomato: Увы!
Traceback (most recent call last):
  File "snoop.py", line 762, in <module>
    main()
  File "snoop.py", line 733, in main
    file.write(date.strftime("%d/%m/%Yг. в %Hч.%Mм.%Sс."))
UnicodeEncodeError: 'locale' codec can't encode character '\u0433' in position 8: encoding error
```

- Python 3.7.4
- Windows 10
- bash

**Comment by GnuriaN** [comment]
```Traceback (most recent call last):
  File "snoop.py", line 762, in <module>
    main()
  File "snoop.py", line 733, in main
    file.write(date.strftime("%d/%m/%Yг. в %Hч.%Mм.%Sс."))
UnicodeEncodeError: 'locale' codec can't encode character '\u0433' in position 8: encoding error```

Microsoft Windows [Version 10.0.18363.657]
Python 3.7.2
cmd

**Comment by snooppr** [comment]
Для проверки исправления ребята @GnuriaN @samdark  пожалуйста подвердите fix
`git clone https://github.com/snooppr/snoop.git -b test`

Как подвердите исправление солью fix с основной веткой.

**Comment by samdark** [comment]
Попробовал. Намертво виснет на

```
[-] YouPic: Увы!
[-] YouTube: Увы!
[-] Zhihu: Увы!
```

Вероятно, никак не сязано с изначальной проблемой, а связано с таймаутами и недоступностью одного из ресурсов. Но проверить изначальную не могу потому как Zomato после Zhihu.

**Comment by snooppr** [comment]
> Попробовал. Намертво виснет на
> 
> ```
> [-] YouPic: Увы!
> [-] YouTube: Увы!
> [-] Zhihu: Увы!
> ```
> 
> Вероятно, это не связано с изначальной проблемой, связанной с таймаутами и недоступностью одного из ресурсов. Zomato после Zhihu.

У меня нет сейчас возможности проверить на Windows (зависания), в любом случае для этого есть опция `--time 9`. Тайминги это другая проблема.

Вы проверяли патч для win 10 из тестовой ветки?
https://github.com/snooppr/snoop/issues/6#issuecomment-586877509

Он не решает проблему?

**Comment by samdark** [comment]
Да, решает. Можно мёржить.
