### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by hakxcore** [snooppr/snoop#67]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

**Comment by snooppr** [comment]
Not enough information.  At what step does the error occur?  Are you trying to run Snoop from sources on the master branch, or from the snoop_termux branch?  
What version of python and numpy are you using?  What OS?  

You can also run the compiled version of snoop without any problems.

**Comment by hakxcore** [comment]
I am trying to install it according to this [readme](https://github.com/snooppr/snoop/blob/snoop_termux/README.en.md) after executing `$ pip install -r requirements.txt` then its showing an error.
In the installation process when it starts installing `NumPy`, that error is coming.

**Comment by snooppr** [comment]
You are trying to install snoop from readme on android.  OK.  There is no "numpy" package in snoop termux for android.

`$ cat requirements.txt`

beautifulsoup4>=4.9.1
certifi>=2021.10.8
click==8.0.3
colorama==0.4.4
lxml>=4.6.5
playsound==1.2.2
requests>=2.25.1
requests-futures==1.0.0
rich==10.15.2
soupsieve>=2.1
speedtest-cli==2.1.3

You missed an important step:
> `git clone https://github.com/snooppr/snoop -b snoop_termux`

To proceed with the installation on Android, you must use the Android version of Snoop.  Just switch to the Android version and continue with the installation:
`
$ git checkout snoop_termux
`

**Comment by hakxcore** [comment]
Thankyou so much for clarifying me!
