### ISSUE TITLE
Crashing upon executiion

### ISSUE THREAD

**Issue by J775w** [snooppr/snoop#68]
This is referring to the latest release. When executed, the file crashes immediately.

**Comment by snooppr** [comment]
Please provide screenshots of what is happening and what you mean.

**Comment by J775w** [comment]
Hi! I apologize if this is a simple resolution, but I do not speak Russian... Here is a video of what is happening. When I launch snoop.exe, red text appears and it crashes. Also, I am curious, how would I buy the full version of Snoop?

**Comment by J775w** [comment]
https://user-images.githubusercontent.com/119549485/218379914-a060828e-549a-46c6-b3d1-bd33cc6ba276.mp4

**Comment by snooppr** [comment]
Sorry, this is not a mistake.  You are told that you have not selected anything, neither plugins nor search by users.  There is a [readme in English](https://github.com/snooppr/snoop/blob/master/README.en.md) , please check it for how to use the software.

**Comment by J775w** [comment]
Thanks!

**Comment by snooppr** [comment]
> Thanks!

Among other things, the archive with the software contains a short video example of how to run Snoop for beginner users...
