### ISSUE TITLE
В результатах D3.ru и Change.org отображается при поиске любого username

### ISSUE THREAD

**Issue by LazyKarlson** [snooppr/snoop#69]
При поиске любого юзернейма в результатах всегда есть  D3.ru и Change.org.
При переходе по ссылке на change.org - 404 страница браузера
При переходе по ссылке на d3.ru - внутренняя 404 страница d3
В заголовке ответа в обоих случаях - Status Code: 404 Not Found

**Comment by snooppr** [comment]
Можете показать скриншот?

Не существующих ников не находит на упомянутых сайтах.

Вы использовали TOR при поиске?

![Scre](https://user-images.githubusercontent.com/61022210/223098742-08d7208c-ef28-460e-9b91-ae1f98f22a85.png)

**Comment by LazyKarlson** [comment]
![Screenshot_2023-03-06_15-18-22](https://user-images.githubusercontent.com/1873325/223108537-6f5240af-5b25-4305-bae5-b0c4d1a0c2f0.png)

**Comment by LazyKarlson** [comment]
Отбой, разобрался) Я в Беларуси, а change.org и d3.ru заблокированы у белорусских провайдеров. Поэтому был такой результат. Через ВПН ищет корректно.
