### ISSUE TITLE
Версия psutil

### ISSUE THREAD

**Issue by lexezzz** [snooppr/snoop#81]
https://github.com/snooppr/snoop/blob/d798fdcee31867d4422c9cc7901c23ad5cba7b55/requirements.txt#L14C1-L14C14

При установке библиотек из requirements.txt столкнулся с проблемой
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools"...
Windows 11, python 3.9.13

Решилось установкой более свежей версии psutil. Работать начало с версии psutil==5.8.0

**Comment by snooppr** [comment]
@lexezzz psutil==5.8.0 требует на windows 11 какие-либо зависимости?

**Comment by lexezzz** [comment]
> @lexezzz psutil==5.8.0 требует на windows 11 какие-либо зависимости?

Нет
