### ISSUE TITLE
Username with dot

### ISSUE THREAD

**Issue by cortodamon** [snooppr/snoop#83]
Usernames in the form:
john.smith

don't seem to be working, or are they also included in the "john smith" form?
And if so, is there a way to only be searching for john.smith,

Thanks!

**Comment by snooppr** [comment]
> When searching, I limit some special characters, for example, "dot" or "hash" (but not all).
 This is done specifically so that the user does not receive false results in the vast majority of cases.

https://github.com/snooppr/snoop/issues/58
