### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by Begginenr** [snooppr/snoop#95]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/snoop/snoop.py", line 145, in <module>
    os.makedirs(f"{dirpath}/results", exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 1] Operation not permitted: '/data/data/com.termux/files/home/storage/shared/snoop'
![IMG_20240723_133854](https://github.com/user-attachments/assets/7263981b-6785-4fa5-8f88-f32d401b71c6)

**Comment by snooppr** [comment]
An error on your part: you didn’t read the installation method on Android/Termux (described in detail in RU/EN languages), [here, for example in EN.](https://github.com/snooppr/snoop/blob/master/README_android.en.md)

> $ termux-setup-storage

With this command you give access to the storage to the Termux application. The only exception is Android 11 (a well-known bug, when this command does not work, you need to grant permission in the classic way: go to Android settings, select the Termux application and grant permission to access the storage).
