### ISSUE TITLE
Problem opening the results

### ISSUE THREAD

**Issue by Wolfix-coder** [snooppr/snoop#96]
Нello I had some problems with your tool after scanning nickname files from .html and .txt do not open properly![Screenshot_2024-08-10-21-54-36-028_com.android.htmlviewer.jpg](https://github.com/user-attachments/assets/e95fc25d-78d7-4ac5-8787-314df419b982)

.

**Comment by snooppr** [comment]
According to the documentation/readme, you should first configure Termux itself to open files. Next, the results on Android should not be opened with any browser, but with the default html viewer. But you can open, for example, a report not from Termux, but from the Kiwi brpwser file manager, the "/storage/emulated/0/snoop" directory.
