### ISSUE TITLE
Не удалось открыть результаты / Unable to open results

### ISSUE THREAD

**Issue by Kkattsuu** [snooppr/snoop#97]
Ru: При поиске информации по никнейму, после всего сбора информации успешно завершает работу и выдает такую ошибку: 
Не удалось открыть результаты
+
Результаты не сохраняются в "save reports"
Что делать?

En: When searching for information on a nickname, after the entire collection of information, it successfully completes the work and gives the following error:
Unable to open results
+
Results are not saved in "Save Reports"
What to do?

**Comment by snooppr** [comment]
Недостаточно описание "проблемы", чтобы понять что происходит. Какая используется операционная система?, т.е. в каком окружении исрользуется Snoop?. Запуск из исходникоа или запуск сборки?

Кроме того, в зависимости от OS результаты сохраняются сюда: "...snoop/results/nicknames/html/*", а не в " "Save Reports"

Каталог "Save Reports" и должен быть пустым, он заполняется лишь тогда, когда Snoop используется с опцией -S/--save-page (Сохранять найденные странички пользователей в локальные html-файлы), и об этом подробно расписано в документации.
